language: c++
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_script:
  - git clone https://github.com/ISCDtoolbox/Commons.git
  - mkdir Commons/build
  - cd Commons/build
  - cmake ..
  - make 
  - make install
  - cd -
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install ..
  - make
  - make install
  - cd -
notifications:
  email: false
