name: continuous integration

on:
  # run tests on push events
  push:
  # run tests on PR events
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    # Launch a matrix of jobs
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-20.04,macos-10.15]
          compiler: [gcc,clang]

    steps:
      - name: Install gcc on OSX
        if: matrix.compiler == 'gcc' && matrix.os == 'macos-10.15'
        run:|
          brew install gcc

      - name: Install LibCommons
        # LinearElasticity don't build with MSVC
        run: |
          git clone https://github.com/ISCDtoolbox/Commons.git
          cd Commons
          mkdir build
          cd build
          cmake ..
          make install
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}

      # checkout the event branch for automatic workflows
      - uses: actions/checkout@v2
        with:
          path: mshdist

      - name: Configure Mshdist
        run: |
          cmake -Smshdist -Bbuild -DCMAKE_INSTALL_PREFIX=$HOME/install
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}


      - name: Build Mshdist
        run: |
          cmake --build build

      - name: Install Mshdist
        run: |
          cmake --install build
